tempus_build:
  stage: test
  script:
      - cmd /s /c "ci\windows\build_protobuf.bat"
      - mkdir -p build/bin
      - cp /cygdrive/c/libs/bin/libprotobuf.dll build/bin
      - cp /cygdrive/c/osgeo4w64/bin/libpq.dll build/bin
      - cmd /s /c "ci\windows\build_gitlab.bat"
      - ./build/bin/graph_dumper --list
      - createdb -U User tempus_test_db
      - psql -U User -d tempus_test_db -c "create extension postgis"
      - zcat data/tempus_test_db/tempus_test_db.sql.zip | psql -U User -d tempus_test_db
      - for f in data/tempus_test_db/patch.*; do psql -U User -d tempus_test_db < $f; done
      - TEMPUS_DB_OPTIONS="user=User" ./build/bin/test_core.exe
  artifacts:
    paths:
      - build/lib/*
      - build/bin/*
      
