tempus_build:
  stage: test
  script:
      - cmd /s /c "ci\windows\build_gitlab.bat"
      - echo %PATH%
      - echo $PATH
      - createdb -U User tempus_test_db
      - psql -U User -d tempus_test_db -c "create extension postgis"
      - zcat data/tempus_test_db/tempus_test_db.sql.zip | psql -U User -d tempus_test_db
      - for f in data/tempus_test_db/patch.*; do psql -U User -d tempus_test_db < $f; done
      - TEMPUS_DB_OPTIONS="user=User" ./build/bin/test_core.exe

