language: cpp

sudo: required

os:
  - linux

compiler:
  - g++

branches:
  except:
    - test_av

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - ./ci/${TRAVIS_OS_NAME}/before_install.sh

script:
  - ./ci/${TRAVIS_OS_NAME}/script.sh

